# Generated by Django 3.1.3 on 2020-11-30 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('expiration_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
